/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gaming;

import java.awt.Component;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class PlayersInfo extends javax.swing.JFrame {

    /**
     * Creates new form PlayersInfo
     */
    public PlayersInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        info_button = new javax.swing.JButton();
        home_button = new javax.swing.JButton();
        add_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Search_field = new javax.swing.JTextField();
        Salary_search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Platform_Search = new javax.swing.JButton();
        Platforms_c = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel7.setBackground(new java.awt.Color(255, 0, 0));

        info_button.setBackground(new java.awt.Color(255, 255, 255));
        info_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        info_button.setForeground(new java.awt.Color(255, 0, 0));
        info_button.setText("PLAYER INFORMATION");
        info_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_buttonActionPerformed(evt);
            }
        });

        home_button.setBackground(new java.awt.Color(255, 255, 255));
        home_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        home_button.setForeground(new java.awt.Color(255, 0, 0));
        home_button.setText("HOME");
        home_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_buttonActionPerformed(evt);
            }
        });

        add_button.setBackground(new java.awt.Color(255, 255, 255));
        add_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add_button.setForeground(new java.awt.Color(255, 0, 0));
        add_button.setText("ADD PLAYERS");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(home_button, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(info_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(home_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(373, Short.MAX_VALUE)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"101", "Harry", "20000", "Action", "2015", "Mobile"},
                {"102", "Mia", "30000", "Adventure", "2018", "Console"},
                {"103", "Terry", "20000", "Story", "2016", "PC"},
                {"104", "James", "10000", "Role playing", "2019", "Mobile"}
            },
            new String [] {
                "Gamer ID", "Gamer Name", "Salary", "Genre", "Join Date", "Platform"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Search Salary");

        Salary_search.setText("Search");
        Salary_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salary_searchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Join Date");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("4 THIEVES");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("PLAYER INFORMATION");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Search Platform");

        Platform_Search.setText("Search");
        Platform_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Platform_SearchActionPerformed(evt);
            }
        });

        Platforms_c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Platform", "Mobile", "Console", "PC" }));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButton1.setText("Oldest to newest");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButton2.setText("Newest to oldest");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Search_field)
                                    .addComponent(Platforms_c, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton2)
                                        .addGap(34, 34, 34)))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Salary_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Platform_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Search_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Salary_search))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Platforms_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Platform_Search))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem2.setText("Open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("HELP");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void info_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_buttonActionPerformed

    private void home_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_buttonActionPerformed
        GamingInfo gg = new GamingInfo();
        gg.setVisible(true);
        this.dispose();//disposing the current frame
    }//GEN-LAST:event_home_buttonActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        ADDPLAYERS ac = new ADDPLAYERS();
        ac.setVisible(true);//opening new frame
    }//GEN-LAST:event_add_buttonActionPerformed

    private void Salary_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salary_searchActionPerformed
        try {
            int column = 2;
            int rowCount = jTable1.getRowCount();

            // Creating a new array list with 
            ArrayList<Integer> a = new ArrayList<Integer>();

            for (int i = 0; i < rowCount; i++) {
                String value = (String) jTable1.getValueAt(i, column);
                int val = Integer.parseInt(value);
                if (value != null) {
                    a.add(val);
                }
            }
            //looping through the list to find minimum value
            for (int i = 0; i < a.size(); i++) {
                int min = i;
                for (int j = i + 1; j < a.size(); j++) {
                    if (a.get(j).toString().compareTo(a.get(min).toString()) < 0) {
                        min = j;
                    }
                }

                // swapping array values
                Integer temp = a.get(min);
                a.set(min, a.get(i));
                a.set(i, temp);

                // swapping gamerid values
                String id = (String) jTable1.getValueAt(i, 0);
                jTable1.setValueAt(jTable1.getValueAt(min, 0), i, 0);
                jTable1.setValueAt(id, min, 0);

                // swapping gamernames values
                String name = (String) jTable1.getValueAt(i, 1);
                jTable1.setValueAt(jTable1.getValueAt(min, 1), i, 1);
                jTable1.setValueAt(name, min, 1);

                // swapping salary values
                String salary = (String) jTable1.getValueAt(i, 2);
                jTable1.setValueAt(jTable1.getValueAt(min, 2), i, 2);
                jTable1.setValueAt(salary, min, 2);

                // swapping genre values
                String genre = (String) jTable1.getValueAt(i, 3);
                jTable1.setValueAt(jTable1.getValueAt(min, 3), i, 3);
                jTable1.setValueAt(genre, min, 3);

                // swapping join date values
                String date = (String) jTable1.getValueAt(i, 4);
                jTable1.setValueAt(jTable1.getValueAt(min, 4), i, 4);
                jTable1.setValueAt(date, min, 4);

                // swapping platform values
                String platform = (String) jTable1.getValueAt(i, 5);
                jTable1.setValueAt(jTable1.getValueAt(min, 5), i, 5);
                jTable1.setValueAt(platform, min, 5);

            }
            int[] b = new int[rowCount];
            for (int i = 0; i < rowCount; i++) {
                String value = (String) jTable1.getValueAt(i, 2);
                int val = Integer.parseInt(value);
                if (value != null) {
                    b[i] = val;
                }
            }
            //getting value from text field
            String price = Search_field.getText();
            int pr = Integer.parseInt(price);//parsing the value of price to int
            // passing values to BinarySearch method
            int index = BinarySearch(b, 0, b.length - 1, pr);
            if (index == -1) {
                System.out.println("Element not found");
            } else {
                System.out.println("the index is " + index);
            }
            //looping through the table to get values at a certain row and column
            String name = "";
            for (int j = 0; j < 1; j++) {
                name = name + jTable1.getValueAt(index, 1).toString() + "\n";
            }
            String id = "";
            for (int j = 0; j < 1; j++) {
                id = id + jTable1.getValueAt(index, 0).toString() + "\n";
            }
            String Genre = "";
            for (int j = 0; j < 1; j++) {
                Genre = Genre + jTable1.getValueAt(index, 3).toString() + "\n";
            }
            String platform = "";
            for (int j = 0; j < 1; j++) {
                platform = platform + jTable1.getValueAt(index, 5).toString() + "\n";
            }
            Component panel = null;
            //Displaying the output
            JOptionPane.showMessageDialog(panel, "Player id:" + id + "Name:" + name + "Genre:" + Genre
                    + "Platform:" + platform);
        } catch (Exception ex) {
            String Message = "Invalid result";
            JOptionPane msg = new JOptionPane();
            msg.showMessageDialog(this, Message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Salary_searchActionPerformed
    public int BinarySearch(int[] arr, int start, int end, int searchElement) {
       // searching for the inputted value
        while (start <= end) {
            int mid = (start + end) / 2;
            if (searchElement == arr[mid]) {
                return mid;
            } else if (searchElement < arr[mid]) {
                end = mid - 1;
            } else {
                start = mid + 1;
            }

        }

        return -1;
    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //path to the file
        String filePath = "src\\Gaming\\jtable.csv";
        File file = new File(filePath);

        try {
            //reading the file
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setColumnIdentifiers(columnsName);

            Object[] tableLines = br.lines().toArray();
            //looping through the file
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);//adding new row with values in the table
            }

        } catch (Exception ex) {
            String Message = "File cant be opened";
            JOptionPane msg = new JOptionPane();
            msg.showMessageDialog(this, Message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void Platform_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Platform_SearchActionPerformed

        if (Platforms_c.getSelectedIndex() != 0) {
            //creating an arraylist to store values
            ArrayList<Integer> Platform = new ArrayList<Integer>();
            String platform = (String) Platforms_c.getSelectedItem();
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                String cat = (String) jTable1.getValueAt(i, 5);
                if (platform.equals(cat)) {
                    Platform.add(i);//adding values in list
                }

            }
            String plat = "";
            //looping and taking values from the table
            for (int j = 0; j < Platform.size(); j++) {
                plat = plat + jTable1.getValueAt(Platform.get(j), 1).toString() + "\n";
            }
            Component panel = null;
            //displaying the output
            JOptionPane.showMessageDialog(panel, "the name of the people with the particular platform are:\n" + plat);
        }

    }//GEN-LAST:event_Platform_SearchActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();//disposing the current frame
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            //file location
            File help = new File("src\\Gaming\\HELP.pdf");
            if (help.exists()) {
                if (Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(help);
                } else {
                    JOptionPane.showMessageDialog(this, "file format not supported");
                }
            } else {
                JOptionPane.showMessageDialog(this, "file does not exist");
            }
        } catch (Exception e) {
            String Message = "File cant be opened";
            JOptionPane msg = new JOptionPane();
            msg.showMessageDialog(this, Message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if (jRadioButton2.isSelected()) {
            sorting(1, 4);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if (jRadioButton1.isSelected()) {
            sorting(0, 4);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    public void sorting(int num, int column) {
        // count the total number of rows with value

        int rowCount = jTable1.getRowCount();

        // Creating a new array with size count
        Object[] a = new Object[rowCount];
        // Storing the table moduleCode value in array a

        // traversing through table data
        for (int i = 0; i < rowCount; i++) {
            String value = (String) jTable1.getValueAt(i, column);
            if (value != null) {
                a[i] = value;
            }
        }
        // looping hrough the array
        for (int i = 0; i < a.length; i++) {
            int min = i;
            for (int j = i + 1; j < a.length; j++) {
                
                if (num == 0) {
                    if (a[j].toString().compareTo(a[min].toString()) < 0) {
                        min = j;
                    }
                } else {
                    if (a[j].toString().compareTo(a[min].toString()) > 0) {
                        min = j;
                    }
                }
            }

            // swapping array values
            Object temp = a[min];
            a[min] = a[i];
            a[i] = temp;

            // swapping gamerid values
            String id = (String) jTable1.getValueAt(i, 0);
            jTable1.setValueAt(jTable1.getValueAt(min, 0), i, 0);
            jTable1.setValueAt(id, min, 0);

            // swapping gamernames values
            String name = (String) jTable1.getValueAt(i, 1);
            jTable1.setValueAt(jTable1.getValueAt(min, 1), i, 1);
            jTable1.setValueAt(name, min, 1);

            // swapping salary values
            String salary = (String) jTable1.getValueAt(i, 2);
            jTable1.setValueAt(jTable1.getValueAt(min, 2), i, 2);
            jTable1.setValueAt(salary, min, 2);

            // swapping genre values
            String genre = (String) jTable1.getValueAt(i, 3);
            jTable1.setValueAt(jTable1.getValueAt(min, 3), i, 3);
            jTable1.setValueAt(genre, min, 3);

            // swapping join date values
            String date = (String) jTable1.getValueAt(i, 4);
            jTable1.setValueAt(jTable1.getValueAt(min, 4), i, 4);
            jTable1.setValueAt(date, min, 4);

            // swapping platform values
            String platform = (String) jTable1.getValueAt(i, 5);
            jTable1.setValueAt(jTable1.getValueAt(min, 5), i, 5);
            jTable1.setValueAt(platform, min, 5);

        }
    }

    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayersInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayersInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayersInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayersInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayersInfo().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Platform_Search;
    private javax.swing.JComboBox<String> Platforms_c;
    private javax.swing.JButton Salary_search;
    private javax.swing.JTextField Search_field;
    private javax.swing.JButton add_button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton home_button;
    private javax.swing.JButton info_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
